// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	ConfirmStatusDBOperation        OperationName = "ConfirmStatusDB"
	CreateBackupOperation           OperationName = "CreateBackup"
	CreateDBOperation               OperationName = "CreateDB"
	DeleteAppliancePowerOperation   OperationName = "DeleteAppliancePower"
	DeleteBackupOperation           OperationName = "DeleteBackup"
	DeleteDBOperation               OperationName = "DeleteDB"
	GetBackupByApplianceIDOperation OperationName = "GetBackupByApplianceID"
	GetDBOperation                  OperationName = "GetDB"
	GetParameterOperation           OperationName = "GetParameter"
	GetVersionOperation             OperationName = "GetVersion"
	ListDBOperation                 OperationName = "ListDB"
	PutAppliancePowerOperation      OperationName = "PutAppliancePower"
	PutParameterOperation           OperationName = "PutParameter"
	PutVersionOperation             OperationName = "PutVersion"
	RestoreBackupOperation          OperationName = "RestoreBackup"
	UpdateConfigDBOperation         OperationName = "UpdateConfigDB"
	UpdateDBOperation               OperationName = "UpdateDB"
)
