// Code generated by ogen, DO NOT EDIT.

package v1

// setDefaults set default value of fields.
func (s *NosqlApplianceRemarkNosql) setDefaults() {
	{
		val := int(9042)
		s.Port = val
	}
}

// setDefaults set default value of fields.
func (s *NosqlRemarkNosql) setDefaults() {
	{
		val := int(9042)
		s.Port = val
	}
}
