// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

// SetFake set fake values.
func (s *Availability) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = Availability(unwrapped)
}

// SetFake set fake values.
func (s *BadRequestResponse) SetFake() {
	{
		{
			s.IsFatal.SetFake()
		}
	}
	{
		{
			s.Serial.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.ErrorCode.SetFake()
		}
	}
	{
		{
			s.ErrorMsg.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ConflictResponse) SetFake() {
	{
		{
			s.IsFatal.SetFake()
		}
	}
	{
		{
			s.Serial.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.ErrorCode.SetFake()
		}
	}
	{
		{
			s.ErrorMsg.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetParameterResponse) SetFake() {
	{
		{
			s.Nosql.SetFake()
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetParameterResponseNosql) SetFake() {
	{
		{
			s.Parameters = nil
			for i := 0; i < 0; i++ {
				var elem NosqlGetParameter
				{
					elem.SetFake()
				}
				s.Parameters = append(s.Parameters, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *Instance) SetFake() {
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.StatusChangedAt.SetFake()
		}
	}
	{
		{
			s.Host.SetFake()
		}
	}
	{
		{
			s.Hosts = nil
			for i := 0; i < 0; i++ {
				var elem InstanceHostsItem
				{
					elem.SetFake()
				}
				s.Hosts = append(s.Hosts, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *InstanceHost) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.InfoURL.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *InstanceHostsItem) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.InfoURL.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *IsOk) SetFake() {
	var unwrapped bool
	{
		unwrapped = true
	}
	*s = IsOk(unwrapped)
}

// SetFake set fake values.
func (s *NosqlAppliance) SetFake() {
	{
		{
			s.Class.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags.SetFake()
		}
	}
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Plan.SetFake()
		}
	}
	{
		{
			s.Settings.SetFake()
		}
	}
	{
		{
			s.SettingsHash.SetFake()
		}
	}
	{
		{
			s.Remark.SetFake()
		}
	}
	{
		{
			s.Availability.SetFake()
		}
	}
	{
		{
			s.Instance.SetFake()
		}
	}
	{
		{
			s.Disk.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Generation.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.Interfaces = nil
			for i := 0; i < 0; i++ {
				var elem NosqlApplianceInterfacesItem
				{
					elem.SetFake()
				}
				s.Interfaces = append(s.Interfaces, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *NosqlApplianceDisk) SetFake() {
	{
		{
			s.EncryptionAlgorithm.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlApplianceInterfacesItem) SetFake() {
	{
		{
			s.IPAddress.SetFake()
		}
	}
	{
		{
			s.UserIPAddress.SetFake()
		}
	}
	{
		{
			s.HostName.SetFake()
		}
	}
	{
		{
			s.Switch.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlApplianceInterfacesItemSwitch) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Scope.SetFake()
		}
	}
	{
		{
			s.Subnet.SetFake()
		}
	}
	{
		{
			s.UserSubnet.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlApplianceInterfacesItemSwitchSubnet) SetFake() {
	{
		{
			s.NetworkAddress.SetFake()
		}
	}
	{
		{
			s.NetworkMaskLen.SetFake()
		}
	}
	{
		{
			s.DefaultRoute.SetFake()
		}
	}
	{
		{
			s.Internet.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlApplianceInterfacesItemSwitchSubnetInternet) SetFake() {
	{
		{
			s.BandWidthMbps.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlApplianceInterfacesItemSwitchUserSubnet) SetFake() {
	{
		{
			s.DefaultRoute.SetFake()
		}
	}
	{
		{
			s.NetworkMaskLen.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlApplianceRemark) SetFake() {
	{
		{
			s.Nosql.SetFake()
		}
	}
	{
		{
			s.Servers = nil
			for i := 0; i < 0; i++ {
				var elem NosqlApplianceRemarkServersItem
				{
					elem.SetFake()
				}
				s.Servers = append(s.Servers, elem)
			}
		}
	}
	{
		{
			s.Zone.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlApplianceRemarkNosql) SetFake() {
	{
		{
			s.DatabaseEngine.SetFake()
		}
	}
	{
		{
			s.DatabaseVersion = "string"
		}
	}
	{
		{
			s.DefaultUser = "string"
		}
	}
	{
		{
			s.DiskSize.SetFake()
		}
	}
	{
		{
			s.Memory.SetFake()
		}
	}
	{
		{
			s.Nodes = int(0)
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.Storage.SetFake()
		}
	}
	{
		{
			s.Virtualcore.SetFake()
		}
	}
	{
		{
			s.Zone = "string"
		}
	}
}

// SetFake set fake values.
func (s *NosqlApplianceRemarkNosqlDatabaseEngine) SetFake() {
	*s = NosqlApplianceRemarkNosqlDatabaseEngineCassandra
}

// SetFake set fake values.
func (s *NosqlApplianceRemarkNosqlDiskSize) SetFake() {
	*s = NosqlApplianceRemarkNosqlDiskSize102400
}

// SetFake set fake values.
func (s *NosqlApplianceRemarkNosqlMemory) SetFake() {
	*s = NosqlApplianceRemarkNosqlMemory8192
}

// SetFake set fake values.
func (s *NosqlApplianceRemarkNosqlStorage) SetFake() {
	*s = NosqlApplianceRemarkNosqlStorageSSD
}

// SetFake set fake values.
func (s *NosqlApplianceRemarkNosqlVirtualcore) SetFake() {
	*s = NosqlApplianceRemarkNosqlVirtualcore3
}

// SetFake set fake values.
func (s *NosqlApplianceRemarkServersItem) SetFake() {
	{
		{
			s.UserIPAddress = netip.MustParseAddr("127.0.0.1")
		}
	}
}

// SetFake set fake values.
func (s *NosqlApplianceRemarkZone) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlBackup) SetFake() {
	{
		{
			s.BackupId = uuid.New()
		}
	}
	{
		{
			s.BackupDestination = "string"
		}
	}
	{
		{
			s.BackupAt = time.Now()
		}
	}
	{
		{
			s.RestoreAt.SetFake()
		}
	}
	{
		{
			s.Size = int64(0)
		}
	}
	{
		{
			s.DeleteStatus.SetFake()
		}
	}
	{
		{
			s.RestoreStatus.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlBackupResponse) SetFake() {
	{
		{
			s.Nosql.SetFake()
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlBackupResponseNosql) SetFake() {
	{
		{
			s.Backups = nil
			for i := 0; i < 0; i++ {
				var elem NosqlBackup
				{
					elem.SetFake()
				}
				s.Backups = append(s.Backups, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateRequest) SetFake() {
	{
		{
			s.Appliance.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateRequestAppliance) SetFake() {
	{
		{
			s.Class.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Plan.SetFake()
		}
	}
	{
		{
			s.Settings.SetFake()
		}
	}
	{
		{
			s.Remark.SetFake()
		}
	}
	{
		{
			s.UserInterfaces = nil
			for i := 0; i < 0; i++ {
				var elem NosqlCreateRequestApplianceUserInterfacesItem
				{
					elem.SetFake()
				}
				s.UserInterfaces = append(s.UserInterfaces, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateRequestApplianceSettings) SetFake() {
	{
		{
			s.Backup.SetFake()
		}
	}
	{
		{
			s.SourceNetwork = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.SourceNetwork = append(s.SourceNetwork, elem)
			}
		}
	}
	{
		{
			s.Password.SetFake()
		}
	}
	{
		{
			s.ReserveIPAddress = netip.MustParseAddr("127.0.0.1")
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateRequestApplianceSettingsBackup) SetFake() {
	{
		{
			s.Connect = "string"
		}
	}
	{
		{
			s.DayOfWeek.SetFake()
		}
	}
	{
		{
			s.Time.SetFake()
		}
	}
	{
		{
			s.Rotate.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateRequestApplianceSettingsBackupDayOfWeekItem) SetFake() {
	*s = NosqlCreateRequestApplianceSettingsBackupDayOfWeekItemSun
}

// SetFake set fake values.
func (s *NosqlCreateRequestApplianceUserInterfacesItem) SetFake() {
	{
		{
			s.Switch.SetFake()
		}
	}
	{
		{
			s.UserIPAddress1 = netip.MustParseAddr("127.0.0.1")
		}
	}
	{
		{
			s.UserIPAddress2.SetFake()
		}
	}
	{
		{
			s.UserIPAddress3.SetFake()
		}
	}
	{
		{
			s.UserSubnet.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateRequestApplianceUserInterfacesItemSwitch) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateRequestApplianceUserInterfacesItemUserSubnet) SetFake() {
	{
		{
			s.DefaultRoute = "string"
		}
	}
	{
		{
			s.NetworkMaskLen = int(0)
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateResponse) SetFake() {
	{
		{
			s.Appliance.SetFake()
		}
	}
	{
		{
			s.Class.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Plan.SetFake()
		}
	}
	{
		{
			s.Settings.SetFake()
		}
	}
	{
		{
			s.Remark.SetFake()
		}
	}
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Account.SetFake()
		}
	}
	{
		{
			s.Tags.SetFake()
		}
	}
	{
		{
			s.Availability.SetFake()
		}
	}
	{
		{
			s.ServerCount.SetFake()
		}
	}
	{
		{
			s.HiddenRemark.SetFake()
		}
	}
	{
		{
			s.Success.SetFake()
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateResponseAccount) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateResponseHiddenRemark) SetFake() {
	{
		{
			s.PlanSpec.SetFake()
		}
	}
	{
		{
			s.Encripted.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateResponseHiddenRemarkEncripted) SetFake() {
	{
		{
			s.Algorithm.SetFake()
		}
	}
	{
		{
			s.IV.SetFake()
		}
	}
	{
		{
			s.MD5.SetFake()
		}
	}
	{
		{
			s.Associative.SetFake()
		}
	}
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateResponseHiddenRemarkPlanSpec) SetFake() {
	{
		{
			s.Note.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlCreateResponseHiddenRemarkPlanSpecNote) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlGetParameter) SetFake() {
	{
		{
			s.SettingItemId = "string"
		}
	}
	{
		{
			s.SettingItem = "string"
		}
	}
	{
		{
			s.DefaultValue.SetFake()
		}
	}
	{
		{
			s.Description = "string"
		}
	}
	{
		{
			s.ParameterOptions = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.ParameterOptions = append(s.ParameterOptions, elem)
			}
		}
	}
	{
		{
			s.SettingValue.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlGetResponse) SetFake() {
	{
		{
			s.Appliance.SetFake()
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlGetVersionResponse) SetFake() {
	{
		{
			s.Nosql.SetFake()
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlGetVersionResponseNosql) SetFake() {
	{
		{
			s.DatabaseVersion = "string"
		}
	}
	{
		{
			s.UpgradableVersions = nil
			for i := 0; i < 0; i++ {
				var elem NosqlGetVersionResponseNosqlUpgradableVersionsItem
				{
					elem.SetFake()
				}
				s.UpgradableVersions = append(s.UpgradableVersions, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *NosqlGetVersionResponseNosqlUpgradableVersionsItem) SetFake() {
	{
		{
			s.Version = "string"
		}
	}
}

// SetFake set fake values.
func (s *NosqlIsOkResponse) SetFake() {
	{
		{
			s.Nosql.SetFake()
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlIsOkResponseNosql) SetFake() {
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlListResponse) SetFake() {
	{
		{
			s.From = int(0)
		}
	}
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.Total = int(0)
		}
	}
	{
		{
			s.Appliances = nil
			for i := 0; i < 0; i++ {
				var elem NosqlAppliance
				{
					elem.SetFake()
				}
				s.Appliances = append(s.Appliances, elem)
			}
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlOkResponse) SetFake() {
	{
		{
			s.Nosql.SetFake()
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlOkResponseNosql) SetFake() {
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlPutParameter) SetFake() {
	{
		{
			s.SettingItemId = "string"
		}
	}
	{
		{
			s.SettingValue = "string"
		}
	}
}

// SetFake set fake values.
func (s *NosqlPutVersionRequest) SetFake() {
	{
		{
			s.Nosql.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlPutVersionRequestNosql) SetFake() {
	{
		{
			s.Version = "string"
		}
	}
}

// SetFake set fake values.
func (s *NosqlPutVersionResponse) SetFake() {
	{
		{
			s.Nosql.SetFake()
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlPutVersionResponseNosql) SetFake() {
	{
		{
			s.Version.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlRemark) SetFake() {
	{
		{
			s.Nosql.SetFake()
		}
	}
	{
		{
			s.Servers = nil
			for i := 0; i < 0; i++ {
				var elem NosqlRemarkServersItem
				{
					elem.SetFake()
				}
				s.Servers = append(s.Servers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *NosqlRemarkNosql) SetFake() {
	{
		{
			s.DatabaseEngine.SetFake()
		}
	}
	{
		{
			s.DatabaseVersion = "string"
		}
	}
	{
		{
			s.DefaultUser = "string"
		}
	}
	{
		{
			s.DiskSize.SetFake()
		}
	}
	{
		{
			s.Memory.SetFake()
		}
	}
	{
		{
			s.Nodes = int(0)
		}
	}
	{
		{
			s.Port = int(0)
		}
	}
	{
		{
			s.Storage.SetFake()
		}
	}
	{
		{
			s.Virtualcore.SetFake()
		}
	}
	{
		{
			s.Zone = "string"
		}
	}
}

// SetFake set fake values.
func (s *NosqlRemarkNosqlDatabaseEngine) SetFake() {
	*s = NosqlRemarkNosqlDatabaseEngineCassandra
}

// SetFake set fake values.
func (s *NosqlRemarkNosqlDiskSize) SetFake() {
	*s = NosqlRemarkNosqlDiskSize102400
}

// SetFake set fake values.
func (s *NosqlRemarkNosqlMemory) SetFake() {
	*s = NosqlRemarkNosqlMemory8192
}

// SetFake set fake values.
func (s *NosqlRemarkNosqlStorage) SetFake() {
	*s = NosqlRemarkNosqlStorageSSD
}

// SetFake set fake values.
func (s *NosqlRemarkNosqlVirtualcore) SetFake() {
	*s = NosqlRemarkNosqlVirtualcore3
}

// SetFake set fake values.
func (s *NosqlRemarkServersItem) SetFake() {
	{
		{
			s.UserIPAddress = netip.MustParseAddr("127.0.0.1")
		}
	}
}

// SetFake set fake values.
func (s *NosqlSettings) SetFake() {
	{
		{
			s.Backup.SetFake()
		}
	}
	{
		{
			s.SourceNetwork = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.SourceNetwork = append(s.SourceNetwork, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *NosqlSettingsBackup) SetFake() {
	{
		{
			s.Connect = "string"
		}
	}
	{
		{
			s.DayOfWeek.SetFake()
		}
	}
	{
		{
			s.Time.SetFake()
		}
	}
	{
		{
			s.Rotate.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlSettingsBackupDayOfWeekItem) SetFake() {
	*s = NosqlSettingsBackupDayOfWeekItemSun
}

// SetFake set fake values.
func (s *NosqlStatusResponse) SetFake() {
	{
		{
			s.Appliance.SetFake()
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlStatusResponseAppliance) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.SettingsResponse.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlStatusResponseApplianceSettingsResponse) SetFake() {
	{
		{
			s.Nosql.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlStatusResponseApplianceSettingsResponseNosql) SetFake() {
	{
		{
			s.Enabled = true
		}
	}
	{
		{
			s.BootStatus = "string"
		}
	}
	{
		{
			s.DatabaseVersion = "string"
		}
	}
	{
		{
			s.UpgradeVersion.SetFake()
		}
	}
	{
		{
			s.Jobs = nil
			for i := 0; i < 0; i++ {
				var elem NosqlStatusResponseApplianceSettingsResponseNosqlJobsItem
				{
					elem.SetFake()
				}
				s.Jobs = append(s.Jobs, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *NosqlStatusResponseApplianceSettingsResponseNosqlJobsItem) SetFake() {
	{
		{
			s.JobType.SetFake()
		}
	}
	{
		{
			s.JobStatus.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlSuccessResponse) SetFake() {
	{
		{
			s.Appliance.SetFake()
		}
	}
	{
		{
			s.Success.SetFake()
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlUpdateRequest) SetFake() {
	{
		{
			s.Appliance.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlUpdateRequestAppliance) SetFake() {
	{
		{
			s.Class.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Tags.SetFake()
		}
	}
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Settings.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlUpdateRequestApplianceSettings) SetFake() {
	{
		{
			s.Backup.SetFake()
		}
	}
	{
		{
			s.SourceNetwork = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.SourceNetwork = append(s.SourceNetwork, elem)
			}
		}
	}
	{
		{
			s.Password.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlUpdateRequestApplianceSettingsBackup) SetFake() {
	{
		{
			s.Connect = "string"
		}
	}
	{
		{
			s.DayOfWeek.SetFake()
		}
	}
	{
		{
			s.Time.SetFake()
		}
	}
	{
		{
			s.Rotate.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NosqlUpdateRequestApplianceSettingsBackupDayOfWeekItem) SetFake() {
	*s = NosqlUpdateRequestApplianceSettingsBackupDayOfWeekItemSun
}

// SetFake set fake values.
func (s *NotFoundResponse) SetFake() {
	{
		{
			s.IsFatal.SetFake()
		}
	}
	{
		{
			s.Serial.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.ErrorCode.SetFake()
		}
	}
	{
		{
			s.ErrorMsg.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *OptAvailability) SetFake() {
	var elem Availability
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBool) SetFake() {
	var elem bool
	{
		elem = true
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptDateTime) SetFake() {
	var elem time.Time
	{
		elem = time.Now()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptGetParameterResponseNosql) SetFake() {
	var elem GetParameterResponseNosql
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptIPv4) SetFake() {
	var elem netip.Addr
	{
		elem = netip.MustParseAddr("127.0.0.1")
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInstance) SetFake() {
	var elem Instance
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptIsOk) SetFake() {
	var elem IsOk
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNilInstanceHost) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilNosqlApplianceDisk) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilNosqlApplianceInterfacesItemSwitchSubnet) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilNosqlCreateRequestApplianceSettingsBackup) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilNosqlCreateRequestApplianceSettingsBackupDayOfWeekItemArray) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilNosqlSettingsBackup) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilNosqlSettingsBackupDayOfWeekItemArray) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilNosqlUpdateRequestApplianceSettingsBackup) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilNosqlUpdateRequestApplianceSettingsBackupDayOfWeekItemArray) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilString) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilTags) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNosqlAppliance) SetFake() {
	var elem NosqlAppliance
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlApplianceInterfacesItemSwitch) SetFake() {
	var elem NosqlApplianceInterfacesItemSwitch
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlApplianceInterfacesItemSwitchSubnetInternet) SetFake() {
	var elem NosqlApplianceInterfacesItemSwitchSubnetInternet
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlApplianceInterfacesItemSwitchUserSubnet) SetFake() {
	var elem NosqlApplianceInterfacesItemSwitchUserSubnet
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlApplianceRemark) SetFake() {
	var elem NosqlApplianceRemark
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlApplianceRemarkNosql) SetFake() {
	var elem NosqlApplianceRemarkNosql
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlApplianceRemarkZone) SetFake() {
	var elem NosqlApplianceRemarkZone
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlBackupResponseNosql) SetFake() {
	var elem NosqlBackupResponseNosql
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlCreateRequestApplianceUserInterfacesItemUserSubnet) SetFake() {
	var elem NosqlCreateRequestApplianceUserInterfacesItemUserSubnet
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlCreateResponseAccount) SetFake() {
	var elem NosqlCreateResponseAccount
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlCreateResponseHiddenRemark) SetFake() {
	var elem NosqlCreateResponseHiddenRemark
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlCreateResponseHiddenRemarkEncripted) SetFake() {
	var elem NosqlCreateResponseHiddenRemarkEncripted
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlCreateResponseHiddenRemarkPlanSpec) SetFake() {
	var elem NosqlCreateResponseHiddenRemarkPlanSpec
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlCreateResponseHiddenRemarkPlanSpecNote) SetFake() {
	var elem NosqlCreateResponseHiddenRemarkPlanSpecNote
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlGetVersionResponseNosql) SetFake() {
	var elem NosqlGetVersionResponseNosql
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlIsOkResponseNosql) SetFake() {
	var elem NosqlIsOkResponseNosql
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlOkResponseNosql) SetFake() {
	var elem NosqlOkResponseNosql
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlPutVersionResponseNosql) SetFake() {
	var elem NosqlPutVersionResponseNosql
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlRemark) SetFake() {
	var elem NosqlRemark
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlRemarkNosql) SetFake() {
	var elem NosqlRemarkNosql
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlSettings) SetFake() {
	var elem NosqlSettings
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNosqlStatusResponseApplianceSettingsResponseNosql) SetFake() {
	var elem NosqlStatusResponseApplianceSettingsResponseNosql
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPassword) SetFake() {
	var elem Password
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPlan) SetFake() {
	var elem Plan
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPutParameterResponseNosql) SetFake() {
	var elem PutParameterResponseNosql
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptServiceClass) SetFake() {
	var elem ServiceClass
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptSuccess) SetFake() {
	var elem Success
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *Password) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = Password(unwrapped)
}

// SetFake set fake values.
func (s *Plan) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PutParameterRequest) SetFake() {
	{
		{
			s.Nosql.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PutParameterRequestNosql) SetFake() {
	{
		{
			s.Parameters = nil
			for i := 0; i < 0; i++ {
				var elem NosqlPutParameter
				{
					elem.SetFake()
				}
				s.Parameters = append(s.Parameters, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PutParameterResponse) SetFake() {
	{
		{
			s.Nosql.SetFake()
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PutParameterResponseNosql) SetFake() {
	{
		{
			s.Parameters = nil
			for i := 0; i < 0; i++ {
				var elem NosqlPutParameter
				{
					elem.SetFake()
				}
				s.Parameters = append(s.Parameters, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ServerErrorResponse) SetFake() {
	{
		{
			s.IsFatal.SetFake()
		}
	}
	{
		{
			s.Serial.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.ErrorCode.SetFake()
		}
	}
	{
		{
			s.ErrorMsg.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ServiceClass) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = ServiceClass(unwrapped)
}

// SetFake set fake values.
func (s *Success) SetFake() {
	var unwrapped bool
	{
		unwrapped = true
	}
	*s = Success(unwrapped)
}

// SetFake set fake values.
func (s *SuccessResponse) SetFake() {
	{
		{
			s.Success.SetFake()
		}
	}
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Tags) SetFake() {
	var unwrapped []string
	{
		unwrapped = nil
		for i := 0; i < 0; i++ {
			var elem string
			{
				elem = "string"
			}
			unwrapped = append(unwrapped, elem)
		}
	}
	*s = Tags(unwrapped)
}

// SetFake set fake values.
func (s *UnauthorizedResponse) SetFake() {
	{
		{
			s.IsFatal.SetFake()
		}
	}
	{
		{
			s.Serial.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.ErrorCode.SetFake()
		}
	}
	{
		{
			s.ErrorMsg.SetFake()
		}
	}
}
